# Site settings
title: Tony likes to blog
description: Follow me on my pet experiences with doggy treats, toys, & more
keywords: Modern, Blogging, Fun
author: Tony
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
avatar: https://avatars0.githubusercontent.com/u/10645272?v=3&s=460
